[package]
name = "royalties-interface"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "1.18.14"
solana-program = "1.18.14"
solana-sdk = "1.18.14"
spl-associated-token-account = "3.0.2"
spl-token = "6.0.0"
spl-token-2022 = "3.0.2"
spl-token-metadata-interface = "0.3.5"
